### ISSUE TITLE
Docker compose fails to connect to localhost

### ISSUE THREAD

**Issue by dcorney** [FullFact/health-misinfo-shared#35]
### Describe the bug

Running `docker compose` fails.

Solution seems to be to remove `localhost` from both image: lines in the `compose.yaml` (though this should be confirmed).

### To Reproduce

Steps to reproduce the behaviour:

1. run `docker compose up -d  `
2. Observe error:
```
 ✘ raphael_frontend_react Error Get "http://localhost/v2/": dial tcp [::1]:80: connect: connection refused                                                                                         0.2s 
 ✘ raphael_backend_flask Error  context canceled                                                                                                                                                   0.2s 
Error response from daemon: Get "http://localhost/v2/": dial tcp [::1]:80: connect: connection refused
```

### Expected behaviour

The docker image should start running

### Additional context

See [slack thread](https://fullfact.slack.com/archives/CTKKUJQHW/p1715599648512769)

**Comment by ff-dh** [comment]
So I've been working on this on the linked branch. It's an annoying series of events, but after figuring out the obvious, that the frontend runs outside of the container (somewhat annoying but that's how SPAs work) it's almost all working. The only issue I have is getting GOOGLE_APPLICATION_CREDENTIALS into the backend container so that it can actually talk to the vertex API and communicate with Gemini. I have an idea on how to do this but if anyone has any contributions that would be great.

Currently you can run the backend on main locally outside a container with i.e. `USERS=dakota:dakota1 python3 -m raphael_backend_flask.app` outside of a container so, that might just be fine for now?

**Comment by andylolz** [comment]
> Currently you can run the backend on main locally outside a container with i.e. USERS=[…] python3 -m raphael_backend_flask.app outside of a container so, that might just be fine for now?

Nice – this is really useful.

I’ve scrapped my attempt at a dev server start script in #45, and have replaced it with some README instructions that includes this line.
