### ISSUE TITLE
Create persistent storage for transcripts, claims, training data etc.

### ISSUE THREAD

**Issue by dcorney** [FullFact/health-misinfo-shared#6]
### Overview

A simple database with API access will be created as discussed in the [MVP doc](https://docs.google.com/document/d/1aOCGdyM8MrEydwFBSrZoG-6a4IVmB_-KoQ7NYnZjc4Q/edit#heading=h.f3h7fhv2c1fh).

This will provide a simple API to allow storage/retrieval of video transcripts; annotated claims for training; and extracted claims inferred by the final model. 

### Outline requirements - to be finalised

Create three tables:

1. video_transcripts: id, URL, metadata (title/date/topic etc.), transcript (=big block of text, e.g. 5k characters)
	Will retrieve via exact matches of URL or fields of metadata

2. training_claims: text of claim (~ a sentence), any manually added label, reference to video id, timestamp (& UUID?)
	Will retrieve via video id

3. inferred_claims: text of claim, model-added label of harm, model_id (string), reference to video id, timestamp (& UUID?)
	Will retrieve via video id

**Comment by ff-dh** [comment]
On a prior call with David, @JamesMcMinn and I came to the conclusion SQLite is suitable for the database, just a persistent on-disk database with support from the Python stdlib. So it makes sense to have a script that generates the tables and then just build the API with a couple of hardcoded queries. And we don't need to worry about migrations of the data or such because it'll be quicker to just rebuild the db with another run of each video?

**Comment by dcorney** [comment]
Work done for https://github.com/FullFact/health-misinfo-shared/issues/9 completes this issue.
